name: Infrastructure Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: choice
        description: 'Environment'
        required: true
        options: ['dev']

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true  # Ensures any submodules are checked out

  login:
    needs: [checkout]
    runs-on: self-hosted
    steps:
      - name: Azure Login
        run: |
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}

  terraform-init:
    needs: [checkout, login]
    runs-on: self-hosted
    env:
      ARM_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
    steps:
      - name: Terraform Init
        working-directory: ./Infra_Setup_Terraform
        run: terraform init -backend-config="storage_account_name=tfstatessolunistresearch" -backend-config="container_name=tfstate" -backend-config="key=terraform.tfstate"

  terraform-plan:
    needs: [checkout, terraform-init]
    runs-on: self-hosted
    env:
      ARM_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
    steps:
      - name: Terraform Plan
        working-directory: ./Infra_Setup_Terraform
        run: terraform plan --var-file=vars/terraform.tfvars

  terraform-apply:
    needs: [checkout, terraform-init, terraform-plan]
    runs-on: self-hosted
    env:
      ARM_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
    steps:
      - name: Terraform Apply
        working-directory: ./Infra_Setup_Terraform
        run: terraform apply --input=false -auto-approve --var-file=vars/terraform.tfvars

  post-cleanup:
    needs: [checkout, terraform-init, terraform-plan, terraform-apply]
    runs-on: self-hosted
    steps:
      - name: Clean Up
        run: |
          az logout
